### ISSUE TITLE
MQTT Auth via username and password

### ISSUE THREAD

**Issue by apfelflo89** [bluewalk/NukiBridge2Mqtt#13]
Hi,

i was going to test your software, but it lacks in user authentification on the mqtt server.
Are there any plans to implement those as environment variables?

**Comment by bluewalk** [comment]
Hi,

I will have a look at adding it as soon as I’m back from my holidays 👍🏻

**Comment by bluewalk** [comment]
Client authentication now available in release https://github.com/bluewalk/NukiBridge2Mqtt/releases/tag/v1.2.7179.31098

**Comment by apfelflo89** [comment]
Running the docker container, it works, thanks for that!
