### ISSUE TITLE
Support for Nuki Opener

### ISSUE THREAD

**Issue by apfelflo89** [bluewalk/NukiBridge2Mqtt#16]
Hi,

Nuki released their new device called Nuki Opener, with it came API changes, especially the devicetype parameter within URL Calls and in Callbacks.

Are there any plans to support the API changes?
Also see:
https://developer.nuki.io/page/nuki-bridge-http-api-190/4/#heading--callback-list

and changelog:

Changelog v 1.9
06.05.2019
Introduced Device Types and Modes to be able to distinguish between Smart Locks and Openers and their operating modes.

Would love to see those changes

**Comment by bluewalk** [comment]
I have released version 1.3.0.0 that contains support for the opener. As I don't have one I was unable to test it. Please report back if there are any issues.

Docker images are being built and will be available shortly.

**Comment by dickesW** [comment]
Works perfect!
