### ISSUE TITLE
Feature Request: boolean state for locked device

### ISSUE THREAD

**Issue by dickesW** [bluewalk/NukiBridge2Mqtt#25]
Hi @bluewalk,

thanks for your nice bridge - works perfect for me. 

I'm using the mqtt lock integration with home assistant, as the NUKI integration is not as configurable as your bridge and doesn't support callbacks.

https://www.home-assistant.io/integrations/lock.mqtt/

Would be cool if you could add the possibility to have a topic which returns true or false for the device state if locked.
Something like: {deviceId}/device-locked `OR` {deviceName}/device-locked

For the lock:
`true` for `locked`, `false` for `unlocked`

For the opener:
`true` for `online`, `false` for `rto active`

What do you think?

Greetings

**Comment by bluewalk** [comment]
Do you need a specific boolean payload as the `device-state` topic also returns the current state of the lock?

**Comment by dickesW** [comment]
sorry, I just found out, that the state and the command payload needs to be the same for the home assistant mqtt lock to work as expected. So I handeled that in an automaton on my side.
Thx
