### ISSUE TITLE
Error running in docker

### ISSUE THREAD

**Issue by swissmaster1** [bluewalk/NukiBridge2Mqtt#27]
Hi I get the fallowing error when I start the docker image:
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

**Comment by bluewalk** [comment]
On what platform are you trying to run the image? I've seen this error before when I tried running the image on ARM hardware.

**Comment by swissmaster1** [comment]
I run it on Synology Diskstation with Intel based CPU and unix running

**Comment by bluewalk** [comment]
Hmm, I'll investigate after work

**Comment by swissmaster1** [comment]
Server Version: 18.09.6
Kernel Version: 3.10.105

**Comment by bluewalk** [comment]
Can you try to upgrade it? I have no problems running it with version 19.03.8.
I am currently unable to reproduce the error and related errors I can find all refer to older versions of Docker.

**Comment by swissmaster1** [comment]
I can't upgrade. I have to wait until Synology release the docker upgrade :-(.

**Comment by swissmaster1** [comment]
Now it looks that it is running in Docker without that error anymore. Don't know why. I'm receiving mqtt messages form NukiBridge2Mqtt. But when I subscribe to a topic (for example nukibridge/door/device-state) I only get one time a "locked". When I unlock nuki I do not get the "unlock" mqtt message. Don't know the reason.

**Comment by swissmaster1** [comment]
Got it. Didnt define a correct callback. Looks like it is working now.
