### ISSUE TITLE
Enable Doorsensor States

### ISSUE THREAD

**Issue by dickesW** [bluewalk/NukiBridge2Mqtt#29]
Hi @bluewalk,

still very happy with NukiBridge2Mqtt. Thanks!

It would be nice to see the [new Doorsensor States](https://developer.nuki.io/page/nuki-bridge-http-api-1-11/4/#heading--doorsensor-states) also implemented.  Nuki just [released ](https://developer.nuki.io/t/bridge-beta-fw-2-6-0-1-16-0-with-door-sensor-state/6159/13) this a few days ago

Thanks dickesW

**Comment by bluewalk** [comment]
Hi @dickesW, great to hear!

I've just pushed changes to incorporate the door-sensor state. Images are being built at the moment :)

**Comment by dickesW** [comment]
Fastest Feature Release ever :)
Thanks will update asap.
