### ISSUE TITLE
Doorsensor State always "Closed"

### ISSUE THREAD

**Issue by dickesW** [bluewalk/NukiBridge2Mqtt#36]
Hi @bluewalk,

I noticed that my `door-state` never changed to "Opened", when I open the door. 

The callback is triggered and I can see the mqtt topics are sent and received but the `door-state` is always "Closed". Even if I lock while it is opened (to force a new callback trigger) the `door-state` is not changing. 

When I restart the docker while my door is open the new initialisation of the NukiBridge2Mqtt gets the correct value "Opened" - but never changes to "Closed" until a restart of the docker with closed door :)

Thanks for your support!

**Comment by bluewalk** [comment]
Hi,

Can you change the loglevel to debug and post the callback JSON? I assume either something is missing there or spelled differently.
You can do this by having a look at log4net.config, change `<level value="INFO" />` to  `<level value="DEBUG" />` and mount it to /app/log4net.config

Cheers

**Comment by bluewalk** [comment]
Actually, I might have forgotten something code, let me have a look 👍

**Comment by bluewalk** [comment]
New images are being built, can you have a look if this solves the issue?

**Comment by dickesW** [comment]
works for me!
Thanks!
