### ISSUE TITLE
Support callbacks for door Opener ringactions

### ISSUE THREAD

**Issue by dickesW** [bluewalk/NukiBridge2Mqtt#39]
Hi @bluewalk,

everything is working very stable with the latest release - thank you!

Nuki added [support for opener ring actions](https://developer.nuki.io/t/nuki-bridge-firmware-release-notes-public-releases/2797):

> Bridge API: get callbacks for door Opener ringactions which did not trigger a state change (“someone unknown rang the bell”) (needs Opener Firmware 1.5.1 or higher)

Would be nice if NukiBridge2Mqtt could support `ringactionTimestamp` and `ringactionState`. It's [documented here](https://developer.nuki.io/page/nuki-bridge-http-api-1-12/4#heading--lockstate).

Thanks and Greetings

dickesw

**Comment by CaptInsano** [comment]
Would love to see this.

Have an opener but am getting flustrated by the unreliablility of the nuki component in homeassistant, I am about to migrate to this docker image and would love to be able to use opener ringactions as trigger to automations in homeassistant.

Great work dev.

**Comment by bluewalk** [comment]
Hi, I'll try to have a look at it today, this issue totally missed my attention...

**Comment by bluewalk** [comment]
I have added support, you can update the docker image by using the develop tag to test. If it works for you I will merge this to the master branch.

**Comment by dickesW** [comment]
> I have added support, you can update the docker image by using the develop tag to test. If it works for you I will merge this to the master branch.

I cant find a new topic for the ringaction. Where do you publish the info?

**Comment by bluewalk** [comment]
Ah, it's publishing the whole state. Let me add the topic as well, kinda forgot about that one :)

**Comment by bluewalk** [comment]
New build is available, I've also updated the readme with the new topics.

**Comment by dickesW** [comment]
perfect! Thanks!
