### ISSUE TITLE
Request: NukiBridge2Mqtt Hassio Addon

### ISSUE THREAD

**Issue by CaptInsano** [bluewalk/NukiBridge2Mqtt#43]
Any chance of making a Hassio Addon of this app?

I am currently running this app via docker on a seperate server but would love to run it as part of my HASSIO install alongside my  Mosquito Broker and Zigbee2MQTT .

![image](https://user-images.githubusercontent.com/332478/103315929-ed8f5500-4a1e-11eb-990b-90a071596ff4.png)

Obviously, no bother at all if you have no interest in supporting this but it would be great!

Thanks Dev.

**Comment by bluewalk** [comment]
Hi, I totally missed your issue somehow, apologies.

Personally I don't run HA or HASSIO so I won't be able to test it. After a quick google it seems to be able to run docker images as well so you probably don't need a separate server (I guess?). You won't have configuration screens in HASSIO though...
