### ISSUE TITLE
MQTT does not send changes

### ISSUE THREAD

**Issue by dennisoderwald** [bluewalk/NukiBridge2Mqtt#46]
I successfully have the Docker container running and according to MQTT Explorer and Node-RED, the topic "nukibridge/info" is also updated once every 5 min. However, when I unlock the door or perform any other action via the app, nothing happens. The status does not change.

Idea what this can be?

Thanks so much in advance for your diligence and work you put into the project!

**Comment by dennisoderwald** [comment]
Problem solved, I had entered a wrong IP address at callback.

**Comment by quellekatalog** [comment]
I've the same problem... which address to use? Currently, the ip of the docker container is used...

nuki2mqtt               | NukiBridge2Mqtt version 1.5.3.2
nuki2mqtt               | https://github.com/bluewalk/NukiBridge2Mqtt/
nuki2mqtt               | 
nuki2mqtt               | 2021-07-13 07:14:34 +00:00 [INF] [] Starting logic
nuki2mqtt               | 2021-07-13 07:14:34 +00:00 [INF] [] Reading configuration from Environment variables
nuki2mqtt               | 2021-07-13 07:14:34 +00:00 [INF] [] Configuration read
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Connecting to XXX:1883
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] Starting callback listener on http://+:8080/
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] Requesting registered callbacks
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Connected
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Subscribing to nukibridge/discover
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Subscribing to nukibridge/reset
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Subscribing to nukibridge/reboot
nuki2mqtt               | 2021-07-13 07:14:35 +00:00 [INF] [] MQTT: Subscribing to nukibridge/fw-upgrade
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] Registered callback #0: http://docker-container-ip:8080/
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] Checking if callback to http://docker-container-ip:8080/ has already been registered
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] Discovering locks on bridge
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/info
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] Processing device YYY
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Subscribing to nukibridge/YYY/device-action
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Subscribing to nukibridge/quibi/device-action
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/device-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/device-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/door-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/door-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/device-mode
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/device-mode
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/battery-critical
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/battery-critical
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/keypad-battery-critical
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/keypad-battery-critical
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/ring-action-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/ring-action-state
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/timestamp
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/timestamp
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/YYY/ring-action-timestamp
nuki2mqtt               | 2021-07-13 07:14:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/quibi/ring-action-timestamp
nuki2mqtt               | 2021-07-13 07:19:36 +00:00 [INF] [] MQTT: Publishing message to nukibridge/info


Many thanks in advance!

**Comment by bluewalk** [comment]
Hi @quellekatalog, yes you need to use the docker ip but you also need to make sure you bound the port (which I apparently didn't put int he README).

Try to start it with `-p 8080:8080` added, eg 
```
docker run -d --name nukibridge2mqtt \
  -e BRIDGE_TOKEN=123abc \
  -e MQTT_HOST=192.168.1.2 \
  -e BRIDGE_CALLBACK_ADDRESS=docker-host-ip \
  -e BRIDGE_CALLBACK_PORT=8080 \
  -p 8080:8080 bluewalk/nukibridge2mqtt
```

**Comment by bluewalk** [comment]
Have you also set the BRIDGE_CALLBACK_ADDRESS? This is what the software uses to register the callback at the bridge.

You can have a look what is registered at the bridge by visiting `http://bridge-ip:8080/callback/list?token=[token]`, if it's incorrect you can remove the items by visiting `http://bridge-ip:8080/callback/remove?id=0&token=[token]` and add the correct address by visiting `http://bridge-ip:8080/callback/add?url=http://docker-host-ip:8080/callback&token=[token]` (or restart the container, it should register it as long as BRIDGE_CALLBACK_ADDRESS is set correctly.

**Comment by quellekatalog** [comment]
thanks again for your quick response and your suggestion. unfortunately that didn't work either... it really seems that nuki doesn't send any callback, no clue why...

**Comment by quellekatalog** [comment]
works now, had a mixup with the ips: instead of the "docker-host-ip" i wrongly used the "docker-ip"... working now - thanks for your support!
